const podcasts = [
  {
    id: 1,
    title: "Tech Talk Weekly",
    host: "John Doe",
    duration: 40.15,
    size_mb: 37.5,
    category: "Technology",
    description:
      "In this episode, we dive deep into the latest trends in AI, the impact of machine learning, and how it’s changing industries worldwide.",
    encoded_audio:
      "QXVkaW8gZGF0YSBmb3IgVGVjaCBUaWxrIFdlZWtseSBieSBKb2huIERvZQ==",
  },
  {
    id: 2,
    title: "History Unfolded",
    host: "Jane Smith",
    duration: 58.22,
    size_mb: 53.7,
    category: "History",
    description:
      "A captivating journey through the ancient civilizations of Egypt, Greece, and Rome, uncovering lost secrets and forgotten tales.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgSGlzdG9yeSBVbmZvbGRlZA==",
  },
  {
    id: 3,
    title: "Mindful Moments",
    host: "Emily White",
    duration: 30.5,
    size_mb: 28.3,
    category: "Wellness",
    description:
      "This episode focuses on meditation techniques for reducing stress and staying calm in challenging situations.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgTWluZGZ1bCBNb21lbnRzIGluIFdlbGxuZXNz",
  },
  {
    id: 4,
    title: "The Startup Diaries",
    host: "David Brown",
    duration: 45.1,
    size_mb: 42.3,
    category: "Business",
    description:
      "Listen to the real stories of entrepreneurs who have built their startups from scratch. This episode features an interview with a successful tech founder.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgVGhlIFN0YXJ0dXAgRGlhcmllcw==",
  },
  {
    id: 5,
    title: "Global Perspectives",
    host: "Sarah Lee",
    duration: 65.4,
    size_mb: 60.4,
    category: "Politics",
    description:
      "A deep dive into global political issues, exploring international relations, conflicts, and strategies for peace.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgR2xvYmFsIFBlcnNwZWN0aXZl",
  },
  {
    id: 6,
    title: "Urban Exploration",
    host: "Mike Green",
    duration: 38.2,
    size_mb: 35.3,
    category: "Travel",
    description:
      "Exploring the world’s most fascinating cities. In this episode, we take you through hidden gems in Paris that only locals know.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgVXJiYW4gRXhwbG9yYXRpb24=",
  },
  {
    id: 7,
    title: "Creative Conversations",
    host: "Laura Adams",
    duration: 52.3,
    size_mb: 48.3,
    category: "Arts",
    description:
      "This episode features an in-depth discussion on the role of creativity in solving modern problems, featuring a guest artist.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgQ3JlYXRpdmUgQ29udmVyc2F0aW9ucw==",
  },
  {
    id: 8,
    title: "Tech for Good",
    host: "Rachel Green",
    duration: 40.0,
    size_mb: 37.2,
    category: "Technology",
    description:
      "Discover how technology is being used for social good. In this episode, we focus on tech innovations that are addressing environmental issues.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgVGVjaCBmb3IgR29vZA==",
  },
  {
    id: 9,
    title: "Creative Coding",
    host: "Alex Turner",
    duration: 55.7,
    size_mb: 51.2,
    category: "Programming",
    description:
      "This episode is all about using code for creative projects, with practical tips and real-world examples from creative coders.",
    encoded_audio:
      "QXVkaW8gZGF0YSBmb3IgQ3JlYXRpdmUgQ29kaW5nIGZvciBQcm9ncmFtbWluZyBIZWxw",
  },
  {
    id: 10,
    title: "Culinary Secrets",
    host: "Olivia Harris",
    duration: 50.3,
    size_mb: 46.5,
    category: "Food & Drink",
    description:
      "Learn the culinary secrets from top chefs! In this episode, we uncover tips for cooking like a pro at home.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgQ3VsYXJ5IFNlY3JldHM=",
  },
  {
    id: 11,
    title: "The Innovator's Mindset",
    host: "Michael Johnson",
    duration: 43.2,
    size_mb: 39.9,
    category: "Innovation",
    description:
      "In this episode, we explore the mindset of innovators and what drives creative thinking in today’s fast-paced world.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgVGhlIElubm92YXRvciBNaW5kc2V0",
  },
  {
    id: 12,
    title: "Music and Technology",
    host: "Sophie Turner",
    duration: 49.8,
    size_mb: 45.5,
    category: "Music",
    description:
      "Join us as we discuss the intersection of music and technology, featuring interviews with industry professionals.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgTXVzaWMgYW5kIFRlY2hub2xvZ3k=",
  },
  {
    id: 13,
    title: "Business Breakthroughs",
    host: "Chris Martin",
    duration: 62.4,
    size_mb: 57.8,
    category: "Business",
    description:
      "This episode dives into the strategies that successful businesses are using to break through their competition and thrive.",
    encoded_audio:
      "QXVkaW8gZGF0YSBmb3IgQnVzaW5lc3MgQnJlYWt0aHJvdWdocyBmb3Igc3VjY2VzcyBkdXN0cmllcw==",
  },
  {
    id: 14,
    title: "Exploring the Unknown",
    host: "Mark Lee",
    duration: 55.5,
    size_mb: 51.2,
    category: "Science",
    description:
      "Join us as we uncover the latest scientific discoveries, from the depths of the ocean to outer space.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgRXhwbG9yaW5nIHRoZSBVbmtub3du",
  },
  {
    id: 15,
    title: "The Art of Storytelling",
    host: "Anna Collins",
    duration: 42.8,
    size_mb: 39.1,
    category: "Arts",
    description:
      "Explore the art of storytelling and how it shapes our culture, featuring renowned authors and narrators.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgVGhlIEFydCBvZiBTdG9yeXRlbGxpbmc=",
  },
  {
    id: 16,
    title: "Fitness Fundamentals",
    host: "Laura Smith",
    duration: 38.6,
    size_mb: 35.4,
    category: "Health",
    description:
      "Learn the fundamentals of fitness, from strength training to nutrition, and how to build a sustainable workout routine.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgRml0bmVzcyBGdW5kYW1lbnRhbHM=",
  },
  {
    id: 17,
    title: "Future of Education",
    host: "David Wilson",
    duration: 53.3,
    size_mb: 49.0,
    category: "Education",
    description:
      "This episode explores how technology and innovation are reshaping the future of education, from AI in classrooms to virtual learning.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgRnV0dXJlIG9mIEVkdWNhdGlvbg==",
  },
  {
    id: 18,
    title: "Health in the Digital Age",
    host: "Emily Parker",
    duration: 60.1,
    size_mb: 55.5,
    category: "Health",
    description:
      "Discussing how digital tools and telemedicine are revolutionizing healthcare, and what it means for patients and doctors.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgSGVhbHQgaW4gdGhlIERpZ2l0YWwgQWdl",
  },
  {
    id: 19,
    title: "Sustainable Living",
    host: "Rachel Adams",
    duration: 47.7,
    size_mb: 43.9,
    category: "Environment",
    description:
      "In this episode, we talk about sustainable living practices, from eco-friendly homes to reducing your carbon footprint.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgU3VzdGFpbmFibGUgTGl2aW5n",
  },
  {
    id: 20,
    title: "Tech Trends Today",
    host: "Jordan Evans",
    duration: 41.4,
    size_mb: 38.1,
    category: "Technology",
    description:
      "A quick roundup of the most exciting tech trends in the industry, from new gadgets to emerging software.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgVGVjaCBUcmVuZHMgVG9kYXk=",
  },
  {
    id: 21,
    title: "Mastering the Mind",
    host: "Thomas Reed",
    duration: 50.3,
    size_mb: 46.3,
    category: "Self-Improvement",
    description:
      "Explore how mastering your mindset can lead to success in all areas of life, featuring expert psychologists and motivational speakers.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgTWFzdGVyaW5nIHRoZSBNaW5k",
  },
  {
    id: 22,
    title: "Crypto Chronicles",
    host: "Jason Foster",
    duration: 58.2,
    size_mb: 53.7,
    category: "Finance",
    description:
      "In this episode, we dive into the world of cryptocurrency, discussing market trends, the future of digital currency, and expert insights.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgQ3J5cHRvIENocm9uaWNsZXM=",
  },
  {
    id: 23,
    title: "Creative Writing Tips",
    host: "Lisa Taylor",
    duration: 41.1,
    size_mb: 37.8,
    category: "Arts",
    description:
      "Get valuable tips and techniques for creative writing, from crafting compelling characters to building engaging plots.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgQ3JlYXRpdmUgV3JpdGluZyBUaXBo",
  },
  {
    id: 24,
    title: "Fitness for Everyone",
    host: "John Carter",
    duration: 45.4,
    size_mb: 41.7,
    category: "Health",
    description:
      "This episode breaks down fitness for people of all levels, providing easy-to-follow workouts and health tips for a balanced lifestyle.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgRml0bmVzcyBmb3IgRXZlcnlvbWU=",
  },
  {
    id: 25,
    title: "Tech Talk Weekly",
    host: "Eva Wong",
    duration: 52.6,
    size_mb: 48.2,
    category: "Technology",
    description:
      "Stay up-to-date with the latest tech news, from new product releases to breakthroughs in AI and beyond.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgVGVjaCBUb3VrIFdlZWtseQ==",
  },
  {
    id: 26,
    title: "Food for Thought",
    host: "Jessica Brooks",
    duration: 47.2,
    size_mb: 43.1,
    category: "Food",
    description:
      "This episode features discussions on food trends, culinary arts, and interviews with top chefs from around the world.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgRm9vZCBmb3IgVGhvdWdodA==",
  },
  {
    id: 27,
    title: "The Entrepreneur's Journey",
    host: "Michael Lee",
    duration: 54.0,
    size_mb: 49.5,
    category: "Business",
    description:
      "Learn how entrepreneurs overcome challenges and build successful businesses through real-life stories and expert advice.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgVGhlIEVudHJlcHJlbmV1ciBKb3VybmV5",
  },
  {
    id: 28,
    title: "History's Mysteries",
    host: "Olivia Clark",
    duration: 63.5,
    size_mb: 58.2,
    category: "History",
    description:
      "Join us as we uncover the mysteries of history, from lost civilizations to unsolved historical events.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgSGlzdG9yeSVzIE15c3Rlcmllcw==",
  },
  {
    id: 29,
    title: "Eco Warriors",
    host: "Nathan Green",
    duration: 46.7,
    size_mb: 42.9,
    category: "Environment",
    description:
      "A podcast dedicated to environmental issues and how we can take action to protect the planet for future generations.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgRWNvIFdhcnJpb3Jz",
  },
  {
    id: 30,
    title: "Innovation in Education",
    host: "Sophia James",
    duration: 59.8,
    size_mb: 54.8,
    category: "Education",
    description:
      "Discover the innovative approaches that are transforming education, from digital classrooms to personalized learning.",
    encoded_audio: "QXVkaW8gZGF0YSBmb3IgSW5ub3ZhdGlvbiBpbiBFZHVjYXRpb24=",
  },
];
